package app.mithila.makaranda.engine.drik;

import app.mithila.makaranda.core.spi.CalculationEngine;
import app.mithila.makaranda.core.spi.EngineDescriptor;

/**
 * DRIK engine boundary. P2 ports the full VSOP87D/Meeus-47 pipeline here;
 * tables arrive as JSON resources generated by scripts/gen*Tables.py.
 */
public class DrikEngine implements CalculationEngine {
  @Override
  public EngineDescriptor descriptor() {
    return new EngineDescriptor(
        "drik-v1",
        "DRIK",
        "drik-cert-2026-09",
        "VSOP87D planets + Meeus-47 Moon (l,b,r) + IAU1980 nutation + true osculating node",
        "CERTIFIED (Moon l 7.3\", planets <=1.09\", Rahu <=112\" vs PyEphem)");
  }
}
