#!/usr/bin/env python3
"""Generate DRIK certification anchors from PyEphem 4.2.1 (independent ephemeris).
Frame: apparent geocentric ecliptic longitude, equinox of date (PyEphem apparent
equatorial of date + mean obliquity of date). Run: python3 scripts/genDrikCert.py
Output JS is written to packages/core/src/drikCert.js."""
import ephem, json, math, sys
def eps0(y):
    T = (y - 2000) / 100
    return 23 + 26/60 + 21.448/3600 + (-46.8150*T - 0.00059*T*T + 0.001813*T**3)/3600
anchors = []
for y in range(2016, 2031):
    for (mo, d, h) in [(1,15,3),(4,20,9),(7,28,15),(10,11,21)]:
        iso = f"{y}-{mo:02d}-{d:02d}T{h:02d}:00:00+00:00"
        dt = ephem.Date(f"{y}/{mo:02d}/{d:02d} {h:02d}:00:00")
        m = ephem.Moon(); m.compute(dt)
        s = ephem.Sun(); s.compute(dt)
        e = math.radians(eps0(y + (mo-1)/12))
        out = {}
        for tag, b in (("moon", m), ("sun", s)):
            ra, dec = float(b.ra), float(b.dec)
            lam = math.degrees(math.atan2(math.sin(ra)*math.cos(e)+math.tan(dec)*math.sin(e), math.cos(ra))) % 360
            out[tag] = round(lam, 6)
        anchors.append({"iso": iso, **out})
with open("packages/core/src/drikCert.js", "w") as f:
    f.write("// GENERATED by scripts/genDrikCert.py — PyEphem 4.2.1, apparent place, equinox of date.\n")
    f.write("// Do not edit by hand.\n")
    f.write("export const DRIK_CERT_ANCHORS = " + json.dumps(anchors, indent=1) + ";\n")
print("wrote packages/core/src/drikCert.js:", len(anchors), "anchors")
