#!/usr/bin/env python3
"""Generate PLANET certification anchors from PyEphem 4.2.1 (independent ephemeris).
Frame: apparent geocentric ecliptic of date — PyEphem apparent equatorial of
date rotated by mean obliquity of date (same recipe as genDrikCert.py).
Output: packages/core/src/planetCert.js"""
import ephem, json, math, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from iau1980_ref import nutation_deg

def eps0(y):
    T = (y - 2000) / 100
    return 23 + 26/60 + 21.448/3600 + (-46.8150*T - 0.00059*T*T + 0.001813*T**3)/3600

def eps_true(jd_tt, y):
    _dpsi, deps = nutation_deg(jd_tt)
    return eps0(y) + deps

BODIES = {"mercury": ephem.Mercury, "venus": ephem.Venus, "mars": ephem.Mars,
          "jupiter": ephem.Jupiter, "saturn": ephem.Saturn}
anchors = []
# Same 60-epoch grid as DRIK_CERT_ANCHORS (2016–2030, 4/year)
for y in range(2016, 2031):
    for (mo, d, h) in [(1,15,3),(4,20,9),(7,28,15),(10,11,21)]:
        iso = f"{y}-{mo:02d}-{d:02d}T{h:02d}:00:00+00:00"
        dt = ephem.Date(f"{y}/{mo:02d}/{d:02d} {h:02d}:00:00")
        e = math.radians(eps_true(float(dt), y + (mo-1)/12))
        row = {"iso": iso}
        for name, cls in BODIES.items():
            b = cls(); b.compute(dt)
            ra, dec = float(b.ra), float(b.dec)
            lam = math.degrees(math.atan2(math.sin(ra)*math.cos(e)+math.tan(dec)*math.sin(e), math.cos(ra))) % 360
            bet = math.degrees(math.asin(math.sin(dec)*math.cos(e) - math.cos(dec)*math.sin(e)*math.sin(ra)))
            row[name] = {"lam": round(lam, 6), "bet": round(bet, 6)}
        anchors.append(row)

with open("packages/core/src/planetCert.js", "w") as f:
    f.write("// GENERATED by scripts/genPlanetCert.py — PyEphem 4.2.1, apparent place, ecliptic of date.\n")
    f.write("// Do not edit by hand.\n")
    f.write("export const PLANET_CERT_ANCHORS = " + json.dumps(anchors, indent=1) + ";\n")
print("wrote packages/core/src/planetCert.js:", len(anchors), "epochs x", len(BODIES), "planets")
