#!/usr/bin/env python3
"""Generate TRUE-RAHU (ascending lunar node) certification anchors from
PyEphem 4.2.1 — osculating-plane method:

  Reference node at epoch t = ascending node of the plane through PyEphem's
  apparent Moon positions at t-0.25d and t+0.25d (ecliptic of date).
  As the separation -> 0 this converges to the node of the osculating lunar
  orbit; at 0.25d the O(sep^2) plane-curvature error is < 0.01" while the
  plane geometry stays far above PyEphem's position noise. This avoids the
  chord-interpolation artifact of the node's ~6-monthly equation (~2.4').

Output: packages/core/src/rahuCert.js"""
import ephem, json, math, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from iau1980_ref import nutation_deg

def eps0(y):
    T = (y - 2000) / 100
    return 23 + 26/60 + 21.448/3600 + (-46.8150*T - 0.00059*T*T + 0.001813*T**3)/3600

def eps_true(jd_tt, y):
    _dpsi, deps = nutation_deg(jd_tt)
    return eps0(y) + deps

def moon_cart(dt):
    """Apparent Moon unit vector in ecliptic of date."""
    dt = ephem.Date(dt)
    m = ephem.Moon(); m.compute(dt)
    y = dt.tuple()[0] + (dt.tuple()[1]-1)/12.0
    e = math.radians(eps_true(float(dt), y))
    ra, dec = float(m.ra), float(m.dec)
    lam = math.atan2(math.sin(ra)*math.cos(e)+math.tan(dec)*math.sin(e), math.cos(ra))
    bet = math.asin(math.sin(dec)*math.cos(e) - math.cos(dec)*math.sin(e)*math.sin(ra))
    cb = math.cos(bet)
    return [cb*math.cos(lam), cb*math.sin(lam), math.sin(bet)]

def cross(a, b):
    return [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]]

anchors = []
for y in range(2017, 2031):
    for (mo, d, h) in [(1,20,6),(7,2,18)]:
        iso = f"{y}-{mo:02d}-{d:02d}T{h:02d}:00:00+00:00"
        dt = ephem.Date(f"{y}/{mo:02d}/{d:02d} {h:02d}:00:00")
        v1, v2 = moon_cart(dt - 0.25), moon_cart(dt + 0.25)
        n = cross(v1, v2)  # prograde => +z
        node = math.degrees(math.atan2(n[0], -n[1])) % 360
        anchors.append({"iso": iso, "rahu": round(node, 6)})

with open("packages/core/src/rahuCert.js", "w") as f:
    f.write("// GENERATED by scripts/genRahuCert.py — PyEphem 4.2.1 osculating-plane node.\n")
    f.write("// Do not edit by hand.\n")
    f.write("export const RAHU_CERT_ANCHORS = " + json.dumps(anchors, indent=1) + ";\n")
print("wrote packages/core/src/rahuCert.js:", len(anchors), "anchors")
